// GENERATED by scripts/discover.mjs — do not edit. Add a bot: copy a folder in
// projects/. Add data: drop a .md/.txt/.csv into its knowledge/. Give it its own
// voice: copy a file from prompt/ into its prompt/. Then commit.
import f_general_meta from "./general/project.json";
import f_general_instructions from "./general/instructions.md";
import f_general_k0 from "./general/knowledge/about-this-bot.md";
import f_example_co_meta from "./example-co/project.json";
import f_example_co_instructions from "./example-co/instructions.md";
import f_example_co_k0 from "./example-co/knowledge/about.md";
import f_example_co_k1 from "./example-co/knowledge/faq.md";
import f_example_co_k2 from "./example-co/knowledge/pricing.md";
import f_brightside_dental_meta from "./brightside-dental/project.json";
import f_brightside_dental_instructions from "./brightside-dental/instructions.md";
import f_brightside_dental_k0 from "./brightside-dental/knowledge/fees.md";
import f_brightside_dental_k1 from "./brightside-dental/knowledge/patient-advice.md";
import f_brightside_dental_k2 from "./brightside-dental/knowledge/practice.md";
import f_brightside_dental_p0 from "./brightside-dental/prompt/3-personality.md";
import f_ledgerly_support_meta from "./ledgerly-support/project.json";
import f_ledgerly_support_instructions from "./ledgerly-support/instructions.md";
import f_ledgerly_support_k0 from "./ledgerly-support/knowledge/plans-and-billing.md";
import f_ledgerly_support_k1 from "./ledgerly-support/knowledge/product.md";

export const PROJECTS = {
  "general": project(f_general_meta, f_general_instructions, {
    "about-this-bot.md": f_general_k0,
  }, {

  }),
  "example-co": project(f_example_co_meta, f_example_co_instructions, {
    "about.md": f_example_co_k0,
    "faq.md": f_example_co_k1,
    "pricing.md": f_example_co_k2,
  }, {

  }),
  "brightside-dental": project(f_brightside_dental_meta, f_brightside_dental_instructions, {
    "fees.md": f_brightside_dental_k0,
    "patient-advice.md": f_brightside_dental_k1,
    "practice.md": f_brightside_dental_k2,
  }, {
    "3-personality.md": f_brightside_dental_p0,
  }),
  "ledgerly-support": project(f_ledgerly_support_meta, f_ledgerly_support_instructions, {
    "plans-and-billing.md": f_ledgerly_support_k0,
    "product.md": f_ledgerly_support_k1,
  }, {

  }),
};

function stripComments(t) { return String(t || "").replace(/<!--[\s\S]*?-->/g, "").trim(); }

function project(meta, instructions, files, promptOverrides) {
  return {
    ...meta,
    starters: Array.isArray(meta.starters) ? meta.starters.slice(0, 4) : [],
    allowedLinks: Array.isArray(meta.allowedLinks) ? meta.allowedLinks : [],
    instructions: stripComments(instructions),
    files: Object.fromEntries(Object.entries(files || {}).map(([n, t]) => [n, stripComments(t)]).filter(([, t]) => t.length > 0)),
    prompt: Object.fromEntries(Object.entries(promptOverrides || {}).map(([n, t]) => [n, stripComments(t)])),
  };
}

export function getProject(id, fallbackId) {
  return PROJECTS[id] || PROJECTS[fallbackId] || Object.values(PROJECTS)[0];
}

export function listProjects() {
  return Object.entries(PROJECTS).map(([id, p]) => ({
    id, name: p.name, tagline: p.tagline || "", greeting: p.greeting || "", starters: p.starters, mode: p.mode, grounding: p.grounding,
    thinkingWords: Array.isArray(p.thinkingWords) && p.thinkingWords.length ? p.thinkingWords : undefined,
  }));
}
