// Scans YourBots/ and prompt/jobs/ and writes the two generated files the
// engine imports. Runs before every `wrangler dev` and `wrangler deploy`
// (build.command in wrangler.jsonc), and on the Deploy button. Because of this
// file, adding a bot is "copy a folder", adding data is "drop a file", and
// nobody edits code.
import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";

const TEXT = /\.(md|txt|csv)$/i;
const ident = (s) => "f_" + s.replace(/[^a-zA-Z0-9]/g, "_");
const isDir = (p) => existsSync(p) && statSync(p).isDirectory();
const listText = (dir) => (isDir(dir) ? readdirSync(dir).filter((f) => TEXT.test(f) && !f.startsWith(".")).sort() : []);

// ---- YourBots/ → YourBots/index.js ----
// Sidebar order: "order" in project.json (lowest first), then name. Folders starting with _ or . are skipped.
const bots = readdirSync("YourBots").filter((d) => isDir(join("YourBots", d)) && !d.startsWith("_") && !d.startsWith(".") && existsSync(join("YourBots", d, "project.json")))
  .map((d) => { let o = 100; try { o = Number(JSON.parse(readFileSync(join("YourBots", d, "project.json"), "utf8")).order ?? 100); } catch {} return { d, o }; })
  .sort((a, b) => a.o - b.o || a.d.localeCompare(b.d)).map((x) => x.d);
let imports = [], entries = [];
for (const id of bots) {
  const base = join("YourBots", id);
  const meta = JSON.parse(readFileSync(join(base, "project.json"), "utf8"));
  const v = ident(id);
  imports.push(`import ${v}_meta from "./${id}/project.json";`);
  const hasInstr = existsSync(join(base, "instructions.md"));
  if (hasInstr) imports.push(`import ${v}_instructions from "./${id}/instructions.md";`);
  const files = listText(join(base, "knowledge"));
  files.forEach((f, i) => imports.push(`import ${v}_k${i} from "./${id}/knowledge/${f}";`));
  const overrides = listText(join(base, "prompt"));
  overrides.forEach((f, i) => imports.push(`import ${v}_p${i} from "./${id}/prompt/${f}";`));
  const jobOverrides = listText(join(base, "prompt", "jobs"));
  jobOverrides.forEach((f, i) => imports.push(`import ${v}_j${i} from "./${id}/prompt/jobs/${f}";`));
  entries.push(`  ${JSON.stringify(id)}: project(${v}_meta, ${hasInstr ? `${v}_instructions` : '""'}, {
${files.map((f, i) => `    ${JSON.stringify(f)}: ${v}_k${i},`).join("\n")}
  }, {
${overrides.map((f, i) => `    ${JSON.stringify(f)}: ${v}_p${i},`).join("\n")}${jobOverrides.map((f, i) => `\n    ${JSON.stringify("jobs/" + f)}: ${v}_j${i},`).join("")}
  }),`);
  console.log(`bot ${id.padEnd(20)} files: ${files.length}${overrides.length || jobOverrides.length ? `  own prompt files: ${[...overrides, ...jobOverrides.map((f) => "jobs/" + f)].join(", ")}` : ""}${meta.name ? "" : "  ⚠ no name in project.json"}`);
}
writeFileSync("YourBots/index.js", `// GENERATED by scripts/discover.mjs — do not edit. Add a bot: copy a folder in
// YourBots/. Add data: drop a .md/.txt/.csv into its knowledge/. Give it its own
// voice: copy a file from prompt/ into its prompt/. Then commit.
${imports.join("\n")}

export const PROJECTS = {
${entries.join("\n")}
};

function stripComments(t) { return String(t || "").replace(/<!--[\\s\\S]*?-->/g, "").trim(); }

function project(meta, instructions, files, promptOverrides) {
  return {
    ...meta,
    starters: Array.isArray(meta.starters) ? meta.starters.slice(0, 4) : [],
    allowedLinks: Array.isArray(meta.allowedLinks) ? meta.allowedLinks : [],
    instructions: stripComments(instructions),
    files: Object.fromEntries(Object.entries(files || {}).map(([n, t]) => [n, stripComments(t)]).filter(([, t]) => t.length > 0)),
    prompt: Object.fromEntries(Object.entries(promptOverrides || {}).map(([n, t]) => [n, stripComments(t)])),
  };
}

export function getProject(id, fallbackId) {
  return PROJECTS[id] || PROJECTS[fallbackId] || Object.values(PROJECTS)[0];
}

export function listProjects() {
  return Object.entries(PROJECTS).map(([id, p]) => ({
    id, order: Number(p.order ?? 100), name: p.name, tagline: p.tagline || "", greeting: p.greeting || "", starters: p.starters, mode: p.mode, grounding: p.grounding,
    thinkingWords: Array.isArray(p.thinkingWords) && p.thinkingWords.length ? p.thinkingWords : undefined,
  }));
}
`);

// ---- prompt/jobs/ → engine/jobs.generated.js ----
const jobs = listText("prompt/jobs").filter((f) => f.endsWith(".md"));
writeFileSync("engine/jobs.generated.js", `// GENERATED by scripts/discover.mjs — do not edit. Add a job: add a file to prompt/jobs/.
${jobs.map((f, i) => `import j${i} from "../prompt/jobs/${f}";`).join("\n")}
export const JOB_FILES = {
${jobs.map((f, i) => `  ${JSON.stringify(f.replace(/\.md$/, ""))}: j${i},`).join("\n")}
};
`);
console.log(`jobs: ${jobs.map((f) => f.replace(/\.md$/, "")).join(", ")}`);
console.log(`registry: ${bots.length} bots → YourBots/index.js, ${jobs.length} jobs → engine/jobs.generated.js`);
